name: "Browser-Control-Agent"
description: "A agent that can control a headless browser, open pages, tabs, etc. using tools like Playwright. Also capable of downloading files, images and html pages."
agent_url: "http://ohcm_browser_control_agent:10020"
tools:
  - name: "Playwright"
    description: "An agent that can control a headless browser, open pages, tabs, etc. using tools like Playwright. Also capable of downloading files, images and html pages."
    tags: ["browser", "headless browser", "playwright"]
    examples: ["Open the Google homepage"]
    mcp_server: 
      url: "http://ohcm_playwright_mcp:8000/mcp"
      transport: "streamable_http"
meta_prompt: "You are a helpful assistant that can use browser automation tools such as Playwright to control a headless browser."
prompt_file: "browser_control_agent.txt"
