name: "Finance-Agent"
description: "An agent that can gather finance information from the web"
agent_url: "http://ohcm_finance_agent:10020"
skillset:
  - name: "Yahoo Finance"
    description: "An agent that can gather finance information from the web using Yahoo Finance"
    tags: ["finance", "yahoo", "finance information"]
    examples: ["Get the latest news about Apple Inc.", "Get the latest news about Apple Inc., if you can't find the news, try to find it using the search tool"]
    mcp_server: 
      url: "http://ohcm_yfinance_mcp:8000/mcp"
      transport: "streamable_http"
meta_prompt: "You are a helpful assistant that can gather finance information from the web"
prompt_file: "finance_agent.txt"
