name: "Web-Search-Agent"
description: "A agent that can use multiple web search tools such as DuckDuckGo, Serper and others to search and navigate the web"
agent_url: "http://ohcm_web_search_agent:10020"
skillset:
  - name: "DuckDuckGo"
    description: "An agent that can search the web using DuckDuckGo"
    tags: ["search", "web search", "information gathering", "duckduckgo"]
    examples: ["Find me websites with real estate listings in Rotterdam"]
    mcp_server: 
      url: "http://ohcm_duckduckgo_mcp:8000/mcp"
      transport: "streamable_http"
  - name: "Serper"
    description: "An agent that can search the web using Serper"
    tags: ["search", "web search", "information gathering", "serper"]
    examples: ["Find me websites with real estate listings in Rotterdam", "Search for Apple's ticker symbol"]
    mcp_server: 
      url: "http://ohcm_serper_mcp:8000/mcp"
      transport: "streamable_http"
  - name: Playwright
    description: "An agent that can look at web resources using Playwright"
    tags: ["web resources", "playwright", "browser", "scraping", "web scraping", "browser automation", "screenshot", "web navigation"]
    examples: ["Open the website https://www.example.com and take a screenshot"]
    mcp_server: 
      url: "http://ohcm_playwright_mcp:8000/mcp"
      transport: "streamable_http"
meta_prompt: "You are a helpful assistant that can use multiple web search tools such as DuckDuckGo, Serper and others to search and navigate the web"
prompt_file: "web_search_agent.txt"
