version: '3.8'

services:

  agent-inspector:
    build:
      context: .
      dockerfile: Dockerfile.a2a-inspector
    container_name: ohcm_a2a_inspector
    environment:
      - PYTHONPATH=/app
    ports:
      - "9001:9001"          # only expose if you need host access
    volumes:
      - ./src/a2a_servers:/app/a2a_servers:ro
      - ./config:/app/config:ro
    working_dir: /app/backend
    command: uv run -- uvicorn app:app --host 0.0.0.0 --port 9001

  agent-registry:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        POETRY_GROUPS: "a2a"
    container_name: ohcm_agent_registry
    environment:
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - PORT=10000
    ports:
      - "10000:10000"
    volumes:
      - ./src/a2a_servers:/app/a2a_servers
      - ./config:/app/config:ro
    working_dir: /app
    command: python -m a2a_servers.registry
    restart: unless-stopped

  supervisor-agent:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        POETRY_GROUPS: "a2a"
    container_name: ohcm_supervisor_agent
    environment:
      - PYTHONPATH=/app
      - AGENT_NAME=supervisor_agent
      - AGENT_CONFIG_DIR=/app/config/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REGISTRY_URL=http://ohcm_agent_registry:10000
    ports:
      - "10030:10030"
      - "5678:5678"    # debugpy port for VS Code debugging
    volumes:
      - ./src/a2a_servers:/app/a2a_servers
      - ./config:/app/config
    working_dir: /app
    command: >
      sh -c "pip install debugpy &&
              python -Xfrozen_modules=off -m debugpy --listen 0.0.0.0:5678 --wait-for-client -m a2a_servers.supervisor --agent-name supervisor_agent --port 10030"


  communication-agent:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        POETRY_GROUPS: "a2a"
    container_name: ohcm_communication_agent
    environment:
      - PYTHONPATH=/app
      - AGENT_NAME=communication_agent
      - AGENT_CONFIG_DIR=/app/config/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REGISTRY_URL=http://ohcm_agent_registry:10000
    # no ports section, internal only
    ports:
      - "10021:10020"
    volumes:
      - ./src/a2a_servers:/app/a2a_servers
      - ./config:/app/config
    working_dir: /app
    command: python -m a2a_servers.agent --agent-name communication_agent --port 10020
    restart: unless-stopped

  finance-agent:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        POETRY_GROUPS: "a2a"
    container_name: ohcm_finance_agent
    environment:
      - PYTHONPATH=/app
      - AGENT_NAME=finance_agent
      - AGENT_CONFIG_DIR=/app/config/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REGISTRY_URL=http://ohcm_agent_registry:10000
    ports:
      - "10022:10020"

    volumes:
      - ./src/a2a_servers:/app/a2a_servers
      - ./config:/app/config
    working_dir: /app
    command: python -m a2a_servers.agent --agent-name finance_agent --port 10020
    restart: unless-stopped

  web-search-agent:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        POETRY_GROUPS: "a2a"
    container_name: ohcm_web_search_agent
    environment:
      - PYTHONPATH=/app
      - AGENT_NAME=web_search_agent
      - AGENT_CONFIG_DIR=/app/config/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - REGISTRY_URL=http://ohcm_agent_registry:10000
    ports:
      - "10023:10020"
    volumes:
      - ./src/a2a_servers:/app/a2a_servers
      - ./config:/app/config
    working_dir: /app
    command: python -m a2a_servers.agent --agent-name web_search_agent --port 10020
    restart: unless-stopped

networks:
  ${DOCKER_NETWORK}:
    driver: bridge

volumes:
  a2a-config:
