version: '3.8'

services:

  agent-inspector:
    build:
      context: .
      dockerfile: Dockerfile.a2a-inspector
    container_name: ohcm_a2a_inspector
    environment:
      - PYTHONPATH=/app
    ports:
      - "9001:9001"          # only expose if you need host access
    volumes:
      - ./backend/src/a2a_servers:/app/a2a_servers:ro
      - ./backend/config:/app/config:ro
    working_dir: /app/backend
    command: uv run -- uvicorn app:app --host 0.0.0.0 --port 9001

  agent-registry:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        POETRY_GROUPS: "a2a"
        IS_PROD: ${IS_PROD}
        CMD_MODULE: "a2a_servers.registry"
        CMD_ARGS: ""
    container_name: ohcm_agent_registry
    environment:
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - PORT=10000
    ports:
      - "10000:10000"
      - "20001:5678"    # debugpy port for VS Code debugging
    volumes:
      - ./backend/src/a2a_servers:/app/a2a_servers
      - ./backend/config:/app/config:ro
    working_dir: /app
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; urllib.request.urlopen('http://127.0.0.1:10000/health'); print('ok')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  agent-serve:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        POETRY_GROUPS: "a2a"
        IS_PROD: ${IS_PROD}
        CMD_MODULE: "serve.run"
        CMD_ARGS: ""
    container_name: ohcm_agent_serve
    environment:
      - PYTHONPATH=/app
      - HOST=0.0.0.0
      - PORT=9002
      - A2A_AGENT_URL=http://ohcm_supervisor_agent:10020
    ports:
      - "9002:9002"
      - "22222:5678"    # debugpy port for VS Code debugging
    volumes:
      - ./backend/src/serve:/app/serve
    working_dir: /app
    command: uvicorn serve.run:app --host 0.0.0.0 --port 9002
    depends_on:
      supervisor-agent:
        condition: service_healthy

  supervisor-agent:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        POETRY_GROUPS: "a2a"
        IS_PROD: ${IS_PROD}
        CMD_MODULE: "a2a_servers.supervisor"
        CMD_ARGS: "--agent-name supervisor_agent"
        # DEBUG_PY_ARGS: "--wait-for-client"
        HOST: 0.0.0.0
        PORT: 10020
    container_name: ohcm_supervisor_agent
    environment:
      - URL=http://ohcm_supervisor_agent:10020
      - REGISTRY_URL=${REGISTRY_URL}    
      - PYTHONPATH=/app
      - AGENT_NAME=supervisor_agent
      - AGENT_CONFIG_DIR=/app/config/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}    
    ports:
      - "10020:10020"
      - "20002:5678"    # debugpy port for VS Code debugging
    volumes:
      - ./backend/src/a2a_servers:/app/a2a_servers
      - ./backend/config:/app/config
    working_dir: /app
    depends_on:
      agent-registry:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "python", "-c", "import urllib.request,sys; urllib.request.urlopen('http://127.0.0.1:10020/health'); print('ok')"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 40s

  communication-agent:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        POETRY_GROUPS: "a2a"
        IS_PROD: ${IS_PROD}
        CMD_MODULE: "a2a_servers.agent"
        CMD_ARGS: "--agent-name communication_agent"
        # DEBUG_PY_ARGS: "--wait-for-client"
    container_name: ohcm_communication_agent
    environment:
      - URL=http://ohcm_communication_agent:10020
      - REGISTRY_URL=${REGISTRY_URL}
      - PYTHONPATH=/app
      - AGENT_NAME=communication_agent
      - AGENT_CONFIG_DIR=/app/config/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}            
    # no ports section, internal only
    ports:
      - "20003:5678"    # debugpy port for VS Code debugging
    volumes:
      - ./backend/src/a2a_servers:/app/a2a_servers
      - ./backend/config:/app/config
    working_dir: /app
    depends_on:
      agent-registry:
        condition: service_healthy

  finance-agent:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        POETRY_GROUPS: "a2a"
        IS_PROD: ${IS_PROD}
        CMD_MODULE: "a2a_servers.agent"
        CMD_ARGS: "--agent-name finance_agent"
        # DEBUG_PY_ARGS: "--wait-for-client"
    container_name: ohcm_finance_agent
    environment:
      - URL=http://ohcm_finance_agent:10020
      - REGISTRY_URL=${REGISTRY_URL}    
      - PYTHONPATH=/app
      - AGENT_NAME=finance_agent
      - AGENT_CONFIG_DIR=/app/config/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}      
    ports:
      - "20004:5678"    # debugpy port for VS Code debugging
      - "11111:10020" # debugpy port for VS Code debugging
    volumes:
      - ./backend/src/a2a_servers:/app/a2a_servers
      - ./backend/config:/app/config
    working_dir: /app
    depends_on:
      agent-registry:
        condition: service_healthy

  web-search-agent:
    build:
      context: .
      dockerfile: Dockerfile.base
      args:
        POETRY_GROUPS: "a2a"
        IS_PROD: ${IS_PROD}
        CMD_MODULE: "a2a_servers.agent"
        CMD_ARGS: "--agent-name web_search_agent"
        # DEBUG_PY_ARGS: "--wait-for-client"
    container_name: ohcm_web_search_agent
    environment:
      - URL=http://ohcm_web_search_agent:10020
      - REGISTRY_URL=${REGISTRY_URL}    
      - PYTHONPATH=/app
      - AGENT_NAME=web_search_agent
      - AGENT_CONFIG_DIR=/app/config/
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - LANGSMITH_TRACING=${LANGSMITH_TRACING}
      - LANGSMITH_ENDPOINT=${LANGSMITH_ENDPOINT}
      - LANGSMITH_API_KEY=${LANGSMITH_API_KEY}
      - LANGSMITH_PROJECT=${LANGSMITH_PROJECT}            
    ports:
      - "20005:5678"    # debugpy port for VS Code debugging
    volumes:
      - ./backend/src/a2a_servers:/app/a2a_servers
      - ./backend/config:/app/config
    working_dir: /app
    depends_on:
      agent-registry:
        condition: service_healthy

networks:
  ${DOCKER_NETWORK}:
    driver: bridge

volumes:
  a2a-config:
