services:
  db:
    image: postgres:17
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports: 
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app -d app"]
      interval: 5s
      timeout: 5s
      retries: 10

  migrator:
    build:
      context: .
      dockerfile: Dockerfile.goose
    depends_on:
      db:
        condition: service_healthy
    environment:
      GOOSE_DRIVER: postgres
      GOOSE_DBSTRING: postgres://app:app@db:5432/app?sslmode=disable
    volumes:
      - ./db/migrations:/app/migrations   # your .sql files
    working_dir: /app
    entrypoint: ["goose"]                    # default entrypoint; pass cmds via `command:`
    # Example default: run all up migrations
    command: ["-dir", "/app/migrations", "up"]

volumes:
  db_data:
