name: "Communication-Agent"
description: "A agent that can use multiple communication tools such as email, slack and others"
agent_url: "http://host.docker.internal:10020"
tools:
  - name: "Email"
    description: "An agent that can send emails"
    mcp_server: 
      url: "http://ohcm_smtp_mcp:8006/mcp"
      transport: "streamable_http"
  - name: "Calendar"
    description: "An agent that can send calendar events"
    mcp_server: 
      url: "http://ohcm_calendar_mcp:8008/mcp"
      transport: "streamable_http"
meta_prompt: "You are a helpful assistant that can use multiple communication tools such as email, slack and others"
prompt_file: "prompts/communication_agent.txt"
